# CONFIG file, change paths here
reads: "/user_data/men/sepseq/silico_reads/db208test_baseline/processed_cat_reads/"
kraken2db: "/user_data/men/sepseq/databases/2022_05_25_new_kraken_database/kraken2_db_NCBI_gtdb/"
kraken2_genomes: "/user_data/men/sepseq/databases/2022_05_25_new_kraken_database/genomes/refseq/vertebrate_mammalian/GCF_000001405.40/GCF_000001405.40_GRCh38.p14_genomic.fna"

Bowtie2: "Bowtie2/2.4.2-foss-2020b"
Kraken2: "Kraken2/2.1.1-foss-2018a-Perl-5.26.1"

SAMPLE: ["reads_50", "reads_70", "reads_90"]

Kraken2_confidence: "0.2"