# CONFIG file, change paths here
reads: "/user_data/men/sepseq/silico_reads/db208test_baseline/test_read_subset/"
kraken2db: "/user_data/men/sepseq/databases/2022_05_25_new_kraken_database/kraken2_db_human_genome/" #"/user_data/men/sepseq/databases/2022_05_25_new_kraken_database/kraken2_db_NCBI_gtdb/"
kraken2_genomes: "/user_data/men/sepseq/databases/2022_05_25_new_kraken_database/genomes/refseq/viral/GCF_000819615.1/GCF_000819615.1_ViralProj14015_genomic.fna"

Bowtie2: "Bowtie2/2.4.2-foss-2020b"
Kraken2: "Kraken2/2.1.1-foss-2018a-Perl-5.26.1"

SAMPLE: ["reads_50", "reads_70", "reads_90"]

Rlibpath: "/user_data/men/sepseq/R_lib/x86_64-pc-linux-gnu-library/3.6"
Kraken2_confidence: "0.2"